# Generated by Django 5.2.7 on 2025-10-15 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Platform_API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='located_at',
            new_name='created_at',
        ),
    ]
